# Site settings
author: Dr. Mike German
title: The MSG Blog
header-img: img/home-bg.png
email: migerman1@gmail.com
copyright_name: Dr. Mike German
description: > # this means to ignore newlines until "baseurl:"
  Savory thoughts from an energetic startup founder
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: migerman1
github_username:  migerman1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
